Avoid fatal trying to sideload nonexistant images
Trying to pass  WP_Error into `unlink` will cause a fatal, even if
muting output errors:

	Fatal error: Uncaught TypeError: unlink(): Argument #1
	($filename) must be of type string, WP_Error given in
	/usr/src/app/content/plugins/hm-content-import/inc/classes/inserter/wp/class-attachment.php:135